// <auto-generated />
using MAVN.Job.QuorumTransactionWatcher.MsSqlRepositories.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MAVN.Job.QuorumTransactionWatcher.MsSqlRepositories.Migrations
{
    [DbContext(typeof(QtwContext))]
    [Migration("20190620120331_AddGeneralKeyValueTableForBlocksData")]
    partial class AddGeneralKeyValueTableForBlocksData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("quorum_transaction_watcher")
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lykke.Job.QuorumTransactionWatcher.MsSqlRepositories.Entities.BlocksDataEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("blocks_data");
                });
#pragma warning restore 612, 618
        }
    }
}
